services:
  web:
    tty: true
    command: poetry run python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "80:8000"