services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    tty: true
    entrypoint:
      - /entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
          - redis
