# Generated by Django 5.0.7 on 2024-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcbang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=5040)),
                ('seat_count', models.IntegerField()),
                ('pc_spec', models.CharField(max_length=100)),
                ('telecom', models.CharField(max_length=100)),
                ('memo', models.TextField()),
            ],
        ),
    ]
