# Generated by Django 5.0.7 on 2024-07-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_city_pcbang_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="도시 이름"
            ),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="address",
            field=models.CharField(max_length=100, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="ip",
            field=models.GenericIPAddressField(verbose_name="IP"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="memo",
            field=models.TextField(blank=True, verbose_name="메모"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="매장명"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="pc_spec",
            field=models.CharField(max_length=100, verbose_name="PC 사양"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="port",
            field=models.IntegerField(default=5040, verbose_name="포트"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="seat_count",
            field=models.IntegerField(verbose_name="좌석수"),
        ),
        migrations.AlterField(
            model_name="pcbang",
            name="telecom",
            field=models.CharField(max_length=100, verbose_name="통신사"),
        ),
        migrations.CreateModel(
            name="AnalyzeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_count", models.IntegerField(verbose_name="켜져 있는 좌석 수")),
                ("close_count", models.IntegerField(verbose_name="꺼져 있는 좌석 수")),
                (
                    "analyzed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="분석일시"),
                ),
                (
                    "pcbang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyzer.pcbang",
                    ),
                ),
            ],
        ),
    ]
