# Generated by Django 5.0.7 on 2024-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzer",
            "0003_alter_city_name_alter_pcbang_address_alter_pcbang_ip_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyzehistory",
            options={"ordering": ["-analyzed_at"]},
        ),
        migrations.AlterField(
            model_name="analyzehistory",
            name="analyzed_at",
            field=models.DateTimeField(verbose_name="분석일시"),
        ),
    ]
