# Generated by Django 5.0.7 on 2024-08-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0004_alter_analyzehistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="pcbang",
            name="pc_plan_ratio",
            field=models.FloatField(default=100, verbose_name="요금제 비율"),
            preserve_default=False,
        ),
    ]
