# Generated by Django 5.0.7 on 2024-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0005_alter_city_options_pcbang_pc_plan_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcbang",
            name="pc_plan_price",
            field=models.IntegerField(default=1000, verbose_name="요금제 가격"),
            preserve_default=False,
        ),
    ]
